package CorbaModule;


/**
* CorbaModule/MonitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hospital.idl
* vendredi 5 décembre 2025 23 h 42 GMT+01:00
*/

public interface MonitorOperations 
{
  String getStatus ();
} // interface MonitorOperations
