package CorbaModule;

/**
* CorbaModule/MonitorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hospital.idl
* vendredi 5 décembre 2025 23 h 42 GMT+01:00
*/

public final class MonitorHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaModule.Monitor value = null;

  public MonitorHolder ()
  {
  }

  public MonitorHolder (CorbaModule.Monitor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaModule.MonitorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaModule.MonitorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaModule.MonitorHelper.type ();
  }

}
